### ISSUE TITLE
What should the live output show when the code contains errors?

### ISSUE THREAD

**Issue by nixterrimus** [extr0py/oni#154]
Live evaluation is great!  Thank you for building this!

What should the live output show when the code produces errors?  Right now it looks like it keeps showing the previously correct value which is confusing.  Perhaps the output could show "Error" or something else.

I would be very happy if all oni was live evaluation.  I'm *thrilled* that it's a complete vim experience.  Thank you!

**Comment by extr0py** [comment]
Cheers @nixterrimus !

It's great that you're checking out that feature - and funny because I ran into the same issue a day or so ago. It makes it pretty hard to use if it is silently failing.

Right now, the live-eval marker has a yellow border on the side - the design I was considering is:
1) Show a *spinner* while the code section is being evaluated
2) Show a *green border* when the code section has been successfully evaluated
3) Show a *red border* when the code section has failed to evaluate. In addition, in the error case, show the actual error message

The live evaluation handlers actually already return the error message as part of the payload, so the work is really to tweak the overlay to show this extra data in `LiveEvalMarker.tsx`

**Comment by extr0py** [comment]
Besides the red/green color change, I also made the error case show up dashed:
![image](https://cloud.githubusercontent.com/assets/13532591/22108466/2cd819cc-de08-11e6-893b-9e2e5f2bbb6b.png)

Let me know if you have any other ideas or feedback for the feature! It's really a proof-of-concept at the moment, but I think if it is extended there could be some really creative ways to use it. I use it to iterate quickly on prototypes.

**Comment by extr0py** [comment]
Resolved by #155
