### ISSUE TITLE
React error in autocomplete

### ISSUE THREAD

**Issue by keforbes** [extr0py/oni#157]
Autocomplete fails with a React error now.  This actually breaks the functionality and you can't type anymore after it happens.
![react](https://cloud.githubusercontent.com/assets/817509/21869337/5a0755a6-d814-11e6-9fd3-2944eedd3f52.gif)

Here's the error text and a portion of the stack trace.
```
Uncaught Invariant Violation: Minified React error #109;
visit http://facebook.github.io/react/docs/error-decoder.html?invariant=109&args[]=AutoCompletionIcon
for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
updateComponent	@	bundle.js:41151
performUpdateIfNecessary	@	bundle.js:41059
performUpdateIfNecessary	@	bundle.js:33873
runBatchedUpdates	@	bundle.js:33472
perform	@	bundle.js:34236
perform	@	bundle.js:34236
perform	@	bundle.js:33411
flushBatchedUpdates	@	bundle.js:33494
closeAll	@	bundle.js:34302
perform	@	bundle.js:34249
batchedUpdates	@	bundle.js:43502
enqueueUpdate	@	bundle.js:33522
enqueueUpdate	@	bundle.js:42484
enqueueSetState	@	bundle.js:42669
ReactComponent.setState	@	bundle.js:28450
handleChange	@	bundle.js:47590
dispatch	@	bundle.js:47972
setDetailedCompletionEntry	@	bundle.js:26894
setTimeout	@	bundle.js:26572
```

**Comment by extr0py** [comment]
Thanks for the detailed info @keforbes ! Having the gif and the description was very helpful.

Looks like this was a regression from #148  - it was somewhat bizarre. The code completion would come with a value of `constructor`, and it would use the constructor function instead of a React component, which caused that error message. I'll send a PR to address this shortly.
