### ISSUE TITLE
Contributors communication

### ISSUE THREAD

**Issue by TalAmuyal** [extr0py/oni#222]
I find it rather hard to contact and get answers by opening issues (feels a bit disconnected).
Also, I've heard about `gitter`, which should solve the problem (also irc can do the work, but some people prefer not to use it for some reason).

Anyway, I would like to ask extr0py to [create a gitter for this project](https://gitter.im/home/explore#createcommunity).
I hope it well help with communication and thus with the project.

For instance, I would like to contribute to this project and I have some questions. I don't feel comfortable opening an issue per such question. (of course, if the issues way is preferred, that is what I shall do)

**Comment by TalAmuyal** [comment]
P.S: If the gitter option is acceptable, please note the small `github projects?` link at the bottom.

**Comment by jordwalke** [comment]
Gitter is nice, and I would very much recommend Discord.

**Comment by bert88sta** [comment]
I'd be happy with any of the above. As someone who's still learning git and typescript, being able to ask dumb questions without raising issues would help me learn faster and make better contributions.

**Comment by extr0py** [comment]
Cool, gitter seems really popular - Neovim has a gitter, Angular, Vue, Vrapper, etc - I'll create one shortly for this project. It does seem like a much better medium for lightweight questions and more real-time collaboration. I'll set it up this weekend.

Discord looks cool too, didn't know about it. Been using TeamSpeak so long for gaming, maybe it's time to replace it :) I'll stick with gitter for this project just because there is the precedent with Neovim. Thanks for the suggestion!

**Comment by extr0py** [comment]
Alright, added it to the README - and I just saw @TalAmuyal and @bert88sta in the channel, so looks like its working :) Look forward to catching you there! Closing this issue-
