### ISSUE TITLE
Wildmenu option for vim not displaying

### ISSUE THREAD

**Issue by bert88sta** [extr0py/oni#24]
Wildmenu option for vim does not display the options. It does, however, remove the airline information (as it would in the terminal) but the text simply isn't there.

**Comment by extr0py** [comment]
I believe it may be a bug where the `reverse` option isn't correctly handled in all cases in the (msgpack_rpc)[https://neovim.io/doc/user/msgpack_rpc.html] API. 

Are you using a custom colorscheme?

**Comment by bert88sta** [comment]
I'm using solarized dark truecolor, as you suggested (or maybe it was the vimR guys?) to use for gui. Other than that, I don't have any of my own customisations to the color

**Comment by bert88sta** [comment]
The issue went away when I changed to wombat, I'll screw around with some settings and see if I can make it work.

**Comment by bert88sta** [comment]
I tried Molokai with no tweaks, airline disabled, and it has issues. I can't actually take a good screenshot on mac because the meta key seems like it isn't handled

**Comment by bert88sta** [comment]
Update: In a similar vein (pertaining to the colorschemes) certain errors ( use ! to force ) don't display or are highlighted improperly in the statusline.  I think for solarized it might just be that the colors end up hiding the text, as molokai and wombat display them in wrong colors

**Comment by extr0py** [comment]
I was just taking a quick look at this... I believe I can reproduce it reliably like this:
1) :colorscheme monokai
2) :color 
3) Press <TAB>
![image](https://cloud.githubusercontent.com/assets/13532591/21074490/2e217e90-beaf-11e6-832b-75e8939df6ef.png)

The highlight for the second colorscheme is messed up - the background color is okay (it's yellow as it should be), but the foreground color is white instead of gray.

In `Screen.ts` there is some code for handling this:
```
                let foregroundColor = this._currentHighlight.foregroundColor ? this._currentHighlight.foregroundColor : this._foregroundColor
                let backgroundColor = this._currentHighlight.backgroundColor ? this._currentHighlight.backgroundColor : this._backgroundColor

                if (this._currentHighlight.reverse) {
                    const temp = foregroundColor
                    foregroundColor = backgroundColor
                    backgroundColor = temp
                }
```

But `reverse` isn't being set to true, and I don't see it being set.

There's also some interesting stuff happening in `NeovimInstance.ts` where we directly process the message:
```
            } else if (command === "highlight_set") {

                const count = a.length

                const highlightInfo = a[count - 1][0]

                this.emit("action", Actions.setHighlight(
                    !!highlightInfo.bold,
                    !!highlightInfo.italic,
                    !!highlightInfo.reverse,
                    !!highlightInfo.underline,
                    !!highlightInfo.undercurl,
                    highlightInfo.foreground,
                    highlightInfo.background,
                ))
```

Particularly the `a[count - 1]` - there were some cases we were getting multiple highlight calls, and only the last one seemed to be valid. This isn't hitting that case though.

It would be interesting to see how this behaves in other Neovim front-ends - there's a possibility that it is a Neovim bug.

**Comment by bert88sta** [comment]
This is old and no longer relevant with either solarized or default
