### ISSUE TITLE
Cross-communication between multiple instances of Oni

### ISSUE THREAD

**Issue by keforbes** [extr0py/oni#250]
I don't know if this is related to #247 or not so I'm filing it as a new issue.  I've noticed that if I have multiple instances of Oni running, only the most recently launched Oni will display DevTools.  It looks like there's some cross-communication going on between instances and only the last DevTools listener is active.  It's possible there are other listeners that are mixed up as well but the DevTools one is the most noticeable to me.

![multiple_instances](https://cloud.githubusercontent.com/assets/817509/23270990/0aa94daa-f9b3-11e6-8219-4c5ae658397f.gif)

**Comment by extr0py** [comment]
It looks like this is because we are using `Menu.setApplicationMenu` - and the behavior for that is to set the menu for __all__ BrowserWindow instances. When the new window is created, this overrides the previous window.

We have a few options:
- Check to see if there is a way to set the menu per-`BrowserWindow`.' I checked quickly at the electron API docs and it didn't look like it... But it'd be worth a more thorough check because this would be the most straightforward way
- Hook the `activate` or `focus` event of the `BrowserWindow` (can't remember the exact name) - and build the menu at that time. Eventually, we'll want to support this dynamic menu creation anyway - an example of this is that, I'd like to be able to add the language service commands like "Goto Definition", "Quick Fix", etc - and it'd be nice to be able to disable/enable them dynamically based on what the current language plugin supports.
