### ISSUE TITLE
Line Numbers stuck behind

### ISSUE THREAD

**Issue by v3ss0n** [extr0py/oni#281]
![screenshot_20170308_133853](https://cloud.githubusercontent.com/assets/419606/23693817/c9dace3c-0404-11e7-8b66-8e09cba86c29.png)

**Comment by keforbes** [comment]
How are the line numbers stuck behind?  Are you saying that isn't line `53` you're on?  I'm not seeing an issue in that screenshot.

**Comment by v3ss0n** [comment]
5,4,3,2,1,53,1,2,3,4,5 . Is that working as intended? how it works

**Comment by extr0py** [comment]
Ya, by default we set `:set relativenumber`. You can turn this off by running `:set norelativenumber`

This is a somewhat opinionated default, since it isn't on by default in Neovim. I'd be okay changing this back, if it is confusing.

In the meantime, the workaround would be to add `:set norelativenumber` to your `init.vim`.

**Comment by extr0py** [comment]
Thinking about this, I believe it is better to have line numbers (not relative) as the default - that's a bit more friendly to people trying out ONI for the first time. @bert88sta - would you be up for changing our default here? I wanted to give you a bounty as a thank-you for your contributions

**Comment by bert88sta** [comment]
@extr0py: I'll get it taken care of here soon, doing a lot of financial aid business for college at the moment

**Comment by extr0py** [comment]
Cool, no rush, getting financial aid set up is much more important! 💵 💵 Good luck!

**Comment by extr0py** [comment]
This default has been removed, so this is now addressed. Thanks @bert88sta !
