### ISSUE TITLE
Windows Paths Issue?

### ISSUE THREAD

**Issue by am2605** [extr0py/oni#327]
Hi Folks,

Forgive me if this has already been addressed (I did search the issues but couldn't find anything).

I've just installed this on Windows 10, and it looks really quite an exciting project.  However I'm having problems opening files in Windows.

If I select File -> Open and browse to say c:\Users\AMyers\_viminfo, it appears that the backlashes get dropped and it opens a new file called c:UsersAmyers_viminfo - screenshot attached.

Is this a known issue?  If not, is there anything I can do to assist with debugging it?

Thanks!

Andrew.

![capture](https://cloud.githubusercontent.com/assets/119977/24432859/962e3962-1470-11e7-9e4a-f4b0e89615f5.PNG)

**Comment by keforbes** [comment]
You're right, I don't think this has been addressed.  I wrote that feature on Linux and I don't have a Windows box to test with so I'm sure it's my fault.  I'll have to see how Neovim expects this to work.  I'm afraid to just blindly replace `\` with `/` since paths with spaces might be sent with `\ ` (`<backslash><space>`).  I might be able to quote the path, though we're already quoting the whole command with `execute ":e <file>"` under the hood and if I try quoting the path with `'` that would probably prevent variables from being expanded (if that matters).  And yes, I'm just rambling at this point.

As a potential workaround, try using the Fuzzy Finder with `<Ctrl-P>` and see if that opens files correctly.

If you're willing to look at the code to debug it, `Menu.js` is sending `":e " + name` to `index.ts` which executes `"exec \"" + command + "\""`.  There's probably some combination of quotes or string replacements we can do on that string.  If Fuzzy Finder works, you an compare that with `QuickOpen.ts` which is running `"e! " + fullPath`.

**Comment by am2605** [comment]
Thank you for the reply.  Fuzzy Finder does work so that's a good 
workaround.

I have made a change to QuickOpen.tsx which has made it work, but I"m 
not sure if there's any other conseqences of this.  The change is:

Line 358: change from

instance.command("exec \"" + message + "\"")

to

instance.command("exec " + JSON.stringify(message) + "")

**Comment by justinmk** [comment]
> instance.command("exec " + JSON.stringify(message) + "")

In this case, that's an improvement because the `\` slashes look like escape characters to the vim command processor, since the message is dumped as a raw string to `:exec`...

But the filename arg should also be wrapped in vim's `fnameescape()`...

This seems harder than it should be :<

**Comment by extr0py** [comment]
Thanks all for the detailed investigation, and @am2605 for reporting this! I'm able to repro this on Windows as well so I can test out some of the fixes

It seems like based on the notes on `path` here: https://nodejs.org/api/path.html that Windows will support both styles of path characters - `\` and `/`, however the node APIs only return `\`, and this causes problems for VIM.

I think a reasonable workaround is to coerce those slashes to `/`, which should have no impact on Mac/Linux AFAIK. I imagine there are other places we're hitting this issue as well

One other issue is that the `name` argument from `openDialog` in `Menu.js` is actually an array of strings - so there is a chance that we could get more than one filename (although based on the current args, I don't think this is the case). I'll open a PR for the fix I tested out for some feedback.

I realized I mostly use `QuickOpen` or `:e {file}` in my workflow so no wonder I haven't hit this. This is probably the very first thing most people try though when testing a new editor... would be a rocky first impression!

**Comment by keforbes** [comment]
> One other issue is that the name argument from openDialog in Menu.js is actually an array of strings - so there is a chance that we could get more than one filename (although based on the current args, I don't think this is the case).

https://github.com/electron/electron/blob/master/docs/api/dialog.md
I'm not setting `multiSelections` to `true` so I believe we're guaranteed there will only be one result from the `showOpenDialog()` call.

**Comment by extr0py** [comment]
Good point, you're right, we shouldn't have to worry about the multi-selection case for now.

**Comment by am2605** [comment]
Thank you so much for your quick fix.  I have just checked out the branch with #328 and it has resolved the issue.

This is an awesome project - kudos to all involved.

**Comment by extr0py** [comment]
Cheers, thanks for validating the fix and the kind words!
