### ISSUE TITLE
Vim-plug with oni on windows

### ISSUE THREAD

**Issue by John0x** [extr0py/oni#341]
Hey, I wan to add the LanguageClient-neovim plugin to my Oni, since I need support for the Rust Language, but in order to do that, I need to install vim-plugin, how can I do that?
I'm on windows 10 64bit

**Comment by extr0py** [comment]
Hi @John0x , thanks for trying out the project! One of the long-standing goals is to have tight-knit integration with the language server protocol - and we're tracking this with #6 

There are a couple of things you'd need to do:

### Load `init.vim` 

By default, Oni does not load the `init.vim`, in order to avoid collisions with Oni's settings. You can set the `oni.loadInitVim` configuration value to try by doing the following:
- Open Oni
- File -> Preferences -> Edit Oni Config
- Add an entry that looks like:
```
   "oni.loadInitVim": true,
```

Then, as long as you've installed vim-plug plus the plugins as described here: https://github.com/junegunn/vim-plug

You should be all set.

**Comment by extr0py** [comment]
I realized that the Neovim binary that is packaged with Windows does not include Python support, but vim-plug requires Python. Are you able to run the `LanguageClient-neovim` with neovim-qt?

I think we would need another configuration option for this - the ability to specify an alternate neovim binary - something like `oni.neovimPath`, which we don't have yet.

**Comment by justinmk** [comment]
FWIW, vim-plug won't require python once we fix the remaining Windows bug in nvim core. That will be done this week.

**Comment by extr0py** [comment]
Nice, that's great news!

**Comment by keforbes** [comment]
@justinmk, can you tell us what "the remaining Windows bug in nvim core" is so we can follow its progress?

**Comment by justinmk** [comment]
@keforbes https://github.com/neovim/neovim/pull/6359 (if you can try that PR, that's also helpful. But it's only waiting on cleanup and merge, which has been "my next priority" for a week now...)

**Comment by keforbes** [comment]
It looks like neovim/neovim#6359 was closed in preference to neovim/neovim#6387 which was closed in preference to neovim/neovim#6497 which was merged in two days ago.  So it's possible this issue has been resolved in the latest neovim build.

**Comment by keforbes** [comment]
It looks like the "python dependency on windows" portion of this issue has been addressed (Neovim fix committed, new build of Oni created) and the Rust portion of the request is tracked in #385.  @extr0py, can this issue be closed?

**Comment by extr0py** [comment]
Thanks @keforbes! Yes, let's use #385 to track Rust language support, given that the python dependency is now addressed. I'll go ahead and close this out.
