### ISSUE TITLE
Mac: Create way to add Oni to $PATH

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#346]
I'm not sure what the best practice on Mac is, but similar to #344 on Windows, there should be an option to add `Oni` to the `$PATH` variable so that it is accessible from the terminal.

VSCode has an interesting way of handling this:
https://code.visualstudio.com/docs/setup/mac
![image](https://cloud.githubusercontent.com/assets/13532591/24614788/2f9257d6-1841-11e7-886c-6512bf83cc8a.png)

By exposing a command in the command palette to install/uninstall the command.

**Comment by bert88sta** [comment]
After npm install, nom run build, and nom link, I discovered by accident that I could run Oni from anywhere in terminal, and even on Spotlight. Is this not the case for other installation methods?

**Comment by keforbes** [comment]
It is the `npm link` command which is adding `oni` to your `$PATH`.  The current installer is not performing an equivalent operation.

**Comment by keforbes** [comment]
For what it's worth, all that command does in vscode is creates a symlink to `/usr/local/bin/code`.  And it only enables that "Shell Command" `if (process.platform === 'darwin') {`.  I guess we could put a similar command in our Command Palette since users don't get to answer any questions during install on a Mac.

Or, on first launch (on Mac) we could pop-up a prompt to the user asking "would you like to install 'oni' in your $PATH?" and set a flag in `config.js` so the question is never asked again on future launches regardless of the answer.  I'm not sure which behavior Mac people would prefer; maybe we should do both, prompt at first launch and add command to palette so they can change it later.

**Comment by keforbes** [comment]
I was going to work on this issue since it seemed pretty straightforward, especially since we can use vscode's implementation as a starting point.  Unfortunately, after looking a bit closer, I found this:
https://github.com/Microsoft/vscode/blob/92ee0d1e067ae70706cddaa6feca9a7659aa4d90/src/vs/workbench/parts/cli/electron-browser/cli.contribution.ts#L101

vscode is running `osascript` to prompt the user for administrator privileges to write to `/usr/local/bin`.  I thought I could just create a symlink, I didn't think about the fact that it would be to a restricted directory.  So I guess someone who actually owns a Mac would need to implement this to make sure they get that osascript right.

If anyone cares, this is what I was going to add after the `commands[]` declaration (line 67) in `Commands.ts`:
```
    if (Platform.isMac()) {
        if (fs.existsSync("/usr/local/bin/oni")) {
            commands.push(new CallbackCommand("oni.config.removeFromPath", "Remove from $PATH", "Disable executing 'oni' from terminal or Spotlight", () => {
                fs.unlink("/usr/local/bin/oni")
            }))
        } else {
            commands.push( new CallbackCommand("oni.config.addToPath", "Add to $PATH", "Enable executing 'oni' from terminal or Spotlight", () => {
                # TODO: prompt for admin privileges (osascript?)
                fs.symlink("/Applications/Oni.app/Contents/MacOS/Oni", "/usr/local/bin/oni")
            }))
        }
    }
```
Also, there's probably a more clever way to determine the name of the currently running executable rather than hardcoding `/Applications/Oni.app`.  I hope this might help someone else take the feature to completion; I can't take it any further since I don't own a Mac.

**Comment by jordwalke** [comment]
You can have a separate dedicated npm package whose only job is to create two global binaries `oni` and `oni-dev` which will open the installed `/Applications/Oni`.

I would heavily discourage those binaries being written in JS as that adds a considerable amount of startup time (100+ms). I would use a small shell script that uses some node features to work on either windows (cmd) or bash(*nix).

**Comment by extr0py** [comment]
@keforbes , I'm really impressed with how you take on these issues from a Linux machine (both this and the Windows installer issue!). Good find, it does seem like we'd need to leverage `osascript` to bump the privileges. I like the symlink strategy a lot. Thanks for looking into this, it doesn't seem like we're too far away from a solution.

@jordwalke  - The separate package approach is interesting, thanks for the suggestion! I'd like to invest more heavily in this in general. There are lots of parts of Oni that could be split and modularized (sort of like how Atom is structured). Reasoning about the architecture this way is excellent for extensibility and helps in reducing couple / increasing cohesion. I've also been thinking about something similiar for the javascript-plugin extensibility story - being able to reuse NPM for that makes a lot of sense. 

There are some things we'll have to think about in terms of leveraging NPM completely (at least on OSX I think you need to use `sudo npm install -g ....` which is super annoying... I didn't know there was a better way until you posted this on twitter: https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md 👍 ). So we might still need to go the `osascript` route to run the NPM command as admin, and do some checks to make sure this is there. And it's not a given that `npm` would be available, so we'd need to handle that case as well.

Another possibility would be to generalize this even further - like an npm package `add-to-path` that would have an API like:
```
import { addToPath, removeFromPath } from "add-to-path"
..
const pathToAdd = "/Applications/Oni.app/Contents/MacOS/Oni"
addToPath("oni", pathToAdd)
..
```

It'd be a helpful abstraction to hide the platform differences (ie, on Windows, maybe it runs some powershell script as admin, and on OSX, it uses osascript to create the symlinks), and would be useful even outside of Oni. 

I actually just checked and it turns out there is already an `add-to-path`, but it looks like it only updates the PATH locally, and only for Windows - bummer!

**Comment by extr0py** [comment]
This was added by @justjoeyuk in #646 . Thanks @justjoeyuk ! Nice find on `sudo-prompt`, that helped... and since we are adding a direct symlink to the binary, it should be fast.
