### ISSUE TITLE
How to integrate fzf to oni Fuzzy Finder?

### ISSUE THREAD

**Issue by saibing** [extr0py/oni#407]
I try to integrate [fzf](https://github.com/junegunn/fzf) to oni Fuzzy Finder by set : 
```json
editor.quickOpen.execCommand = "fzf"
```
But there is no change, oni still use git ls-files

**Comment by extr0py** [comment]
Interesting, I haven't used `fzf` much. If anyone would be up for taking a look at this, `browser\src\Services\QuickOpen.ts` would be a good starting point, particularly this code path:
```
    public show(): void {
        const config = Config.instance()
        const overrriddenCommand = config.getValue("editor.quickOpen.execCommand")
        const exclude = config.getValue("oni.exclude")

        UI.Actions.showPopupMenu("quickOpen", [{
            icon: "refresh fa-spin fa-fw",
            label: "Loading Files...",
            detail: "",
            pinned: false,
        }])

        // Overridden strategy
        if (overrriddenCommand) {
            const files = execSync(overrriddenCommand)
                .toString("utf8")
                .split("\n")
            this._showMenuFromFiles(files)
            return
        }
...
```

A couple of things to sanity-check:
- Is `overriddenCommand` being set correctly?
- Does `fzf` need arguments passed to it? We may need a way to update the `execCommand` string to incorporate the search arguments.
- I wonder if the command is being executed from the correct working directory - it seems like we may need to set the working directory here for it to work as expected.

**Comment by keforbes** [comment]
Woops, didn't mean to click that button...

**Comment by keforbes** [comment]
@saibing, I finally got a chance to look at this.  First of all, you said:
> editor.quickOpen.execCommand = "fzf"

The format actually needs to be in json, so the string should be:
> "editor.quickOpen.execCommand": "fzf"

Now, even with the correct format, this still fails:
> Uncaught Error: Command failed: fzf
> panic: Failed to open /dev/tty
> 
> goroutine 1 [running]:
> github.com/junegunn/fzf/src/tui.openTtyIn(0x551c20)
>       /Users/jg/.vim/plugged/fzf/gopath/src/github.com/junegunn/fzf/src/tui/light.go:35 +0xb0
>github.com/junegunn/fzf/src/tui.NewLightRenderer(0xc420012e40, 0x100, 0x8, 0x610101, 0x562bb8, 0x0, 0xb)
>       /Users/jg/.vim/plugged/fzf/gopath/src/github.com/junegunn/fzf/src/tui/light.go:116 +0x4e
>github.com/junegunn/fzf/src.NewTerminal(0xc4200ac000, 0xc42000af80, 0xc420014730)
>       /Users/jg/.vim/plugged/fzf/gopath/src/github.com/junegunn/fzf/src/terminal.go:311 +0x189
>github.com/junegunn/fzf/src.Run(0xc4200ac000, 0x569ab0, 0x7)
>       /Users/jg/.vim/plugged/fzf/gopath/src/github.com/junegunn/fzf/src/core.go:209 +0xc58
>main.main()
>       /Users/jg/.vim/plugged/fzf/main.go:8 +0x47
>
>    at checkExecSyncError (child_process.js:502:13)

If you look closely at that stack trace, `fzf` is created by `junegunn` and apparently the code is trying to access `/Users/jg/`.  I'm not sure if that's relevant, I just find it odd.

I *can* run `fzf` from the command-line so I'm not sure if Oni is doing something wrong or if fzf is making assumptions which aren't true when run by Oni.

**Comment by keforbes** [comment]
@extr0py, I think the `overriddenCommand` feature is fundamentally flawed.  That external command is only used to fetch the initial set of files.  All filtering is then done in `Reducer.ts:filterMenuOptions()`.  So even if `fzf` has lightning fast filtering and clever algorithms for fuzzy matching, Oni wouldn't use them.

I think if `overriddenCommand` is defined we should probably send `searchString` to it in `filterMenuOptions` and hope the `overriddenCommand` takes the string as an argument.  I'd be happy to make that change if I could get fzf working as an example.  I think we need to launch fzf in a non-interactive mode so we can send it a string (or "") and have it return the filter to us.  I'm just not sure if that's a feature fzf supports.

**Comment by saibing** [comment]
@keforbes , thanks for your answer.

fzf is supported non-interactive mode:

```sh
$ fzf -f  querystring
```

**Comment by extr0py** [comment]
Yes, good point, seems like we need to re-think that flow, and make sure we're re-invoking the external command as the search string is updated. And thanks @saibing for the help with the command line invocation!

Seems like there are a couple of blockers here:

## Issue 1: `overriddenCommand` not running from correct directory

> If you look closely at that stack trace, fzf is created by junegunn and apparently the code is trying to access /Users/jg/. I'm not sure if that's relevant, I just find it odd.

> Anyway, I can run fzf from the command-line so I'm not sure if Oni is doing something wrong or if fzf is making assumptions which aren't true when run by Oni.

I think this is due to us not passing in the current working directory to `fzf`. We should be running the `fzf` command as if it is being run from the current directory open in Oni, but that's not being explicitly - I think that would explain this issue. This can be fixed by changing this in `QuickOpen.ts`:

```
        // Overridden strategy
        if (overrriddenCommand) {
            const files = execSync(overrriddenCommand)
```

to something like:

```
        // Overridden strategy
        if (overrriddenCommand) {
            const files = execSync(overrriddenCommand, { cwd: process.cwd() })
```

Can you try that and see if that resolves that first blocker?

## Issue 2: The search string isn't passed to the overridden command

It seems like right now we just run `execSync` against the `overriddenCommand`.... But we don't inject the searchString. I think the convention in JavaScript is to have templated variables, like ${searchString}. It would be great to add support for this, so that we could specify the config like:

```
editor.quickOpen.execCommand = "fzf -f ${searchString}"
```

Hope that is useful... thanks for your help looking at this, @keforbes ! FYI I also put a small bounty on this, it will be a nice issue to have resolved.
