### ISSUE TITLE
White background on startup

### ISSUE THREAD

**Issue by nzinov** [extr0py/oni#449]
When oni starts up it shows window with white background, which is quite annoying when dark theme is used.

**Comment by extr0py** [comment]
Yes, this is a great point, it really hurts the polish and feel of Oni.

I have this issue tracking some ideas around improving the load flow of Oni: #355 

I'll be investing heavily in polishing and smoothing out the UI as part of the 0.4 milestone.

I'll close this because I believe it is tracked in #355, but feel free to add any suggestions / ideas. Thanks!
