### ISSUE TITLE
Ctrl-p always says it is loading files

### ISSUE THREAD

**Issue by beatscode** [extr0py/oni#467]
The modal box with the label "Loading Files.." hangs whenever I use Ctrl-p shortcut. Am I missing something?

````
module.exports = {
    //add custom config here, such as
    //"oni.useDefaultConfig": true,
    "oni.loadInitVim": true,
    "editor.fontSize": "14px",
    "editor.fontFamily": "Lekton",
    "editor.fullScreenOnStart: true
}
````

**Comment by keforbes** [comment]
This should be addressed by #269.  Basically, our current implementation fetches the list of all filenames under your current directory before displaying anything.  If you have a ton of files under your current working directory it may take awhile.  We're currently excluding `node_modules` by default since that directory is typically huge but you may have other large directories.

You can use the following config option to mitigate the issue:
> oni.exclude - Glob pattern of files to exclude from Fuzzy Finder (Ctrl-P). Defaults to ["\*\*/node_modules/\*\*"]

Hopefully you have a gigantic folder which you could safely exclude as a workaround.  If the `Loading Files...` truly *never* goes away then I don't know what's going wrong, that'd be something new.

**Comment by extr0py** [comment]
A couple additional questions:
- Which platform are you using, @beatscode ? (Windows, OS X, Linux)?
- Which directory are you opening `oni` from? You can use `:pwd` to see.
- Do you see any errors in the developer tools? You can open them using `Control+Shift+P` and then typing "Open DevTools"

**Comment by beatscode** [comment]
- I'm on MacBook pro Sierra 10.12.5
- Your reply made me check the readme again. I initially just downloaded the mac build. I just now ran the build instructions to try again. And that yielded the correct results when running Ctrl+p.
