### ISSUE TITLE
Autocompletions carry over after pressing space

### ISSUE THREAD

**Issue by bert88sta** [extr0py/oni#500]
Autocompletions should be reset or refreshed after a user presses space

**Comment by extr0py** [comment]
Looks like the same issue as #414 - but not specific to YCM - basically all Vim-style completion is affected. This would be really nice to fix because this feels really broken for some using Vim autocompletion...

It looks like we might need to grab the `popupmenu_hide` event from Vim and close in that case.

**Comment by bert88sta** [comment]
This should be a quick fix, I'm just trying to think if there's any weird cases where neovim says to close completions even though oni itself has completions... I think neovim is smarter than us on completions mostly though, so I'll just throw a few lines into the AutoCompletion Service and test it out to see if it's mostly good

**Comment by extr0py** [comment]
Yep, it looks like at the very least we'd want to hook the `popupmenu_hide` event around where we pick up the `popupmenu_show` event. There could definitely be some corner cases since the language-service powered completion gets fired a bit differently from the neovim-powered integration, worth testing around a bit to see if there is any badness. I think the worst case would be the completions would be overwritten by one strategy, if, for example, neovim-completion kicks in after the language service completion.

**Comment by bert88sta** [comment]
Alright, at least in my generic testing it should be good to go. We also need to stop showing a completion that is the same as the word

**Comment by extr0py** [comment]
> Alright, at least in my generic testing it should be good to go. 

Awesome! Look forward to picking up this PR.

> We also need to stop showing a completion that is the same as the word, which I'm not sure how to do

I can help with this piece. We do this for TypeScript / LSP already - I was thinking that handling `popupmenu_hide` might handle this, but there might need to be some special handling in Oni's completion layer.

**Comment by extr0py** [comment]
Fixed by #531 .
