### ISSUE TITLE
Upgrade TypeScript to 2.4.1

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#519]
Looks like there were several breaking changes in this upgrade (lots of compilation errors to be fixed). These will need to be manually addressed.

**Comment by keforbes** [comment]
The compilation errors are actually https://github.com/Microsoft/TypeScript/issues/16772, which can be resolved by also updating `ts-loader`.
So `typescript: 2.4.1` and `ts-loader: 2.2.2`.  I was going to submit a Pull Request with this fix but Oni currently doesn't build due to an unrelated error:
```
ERROR in ./browser/src/Plugins/Api/Oni.ts
Class 'Oni' incorrectly implements interface 'Api'
```
I didn't want to submit a Pull Request with a broken build so I decided to just document the fix here.

**Comment by extr0py** [comment]
Thanks for the investigation, @keforbes ! That helps a lot - I didn't see that issue. I'll take a shot at it and see what's going on with that error.

**Comment by extr0py** [comment]
Temporarily reverting this change, because it looks like there is a regression or a change in the completion behavior after `<` in `.tsx` files.

For example, if I'm typing in `NeovimSurface.tsx`:
```
export class NeovimSurface extends React.PureComponent<R|
```

I'd expect completion to pop open. However, it seems that at least this case and a few others are broken after upgrading to TypeScript 2.4.1, and the completion dialog does not open in this case.

Need to check:
- Is this an open / active issue in the typescript github repo?
- Does it only impact `tsx` files, or does it also impact generics in `ts` files?
- Did it start in 2.3.x or 2.4.x?
