### ISSUE TITLE
Can we use passive event listeners for a bump in scroll performance?

### ISSUE THREAD

**Issue by bert88sta** [extr0py/oni#582]

**Comment by bert88sta** [comment]
The video on this site is a nice comparison, although these may be geared more for touch devices

https://medium.com/@devlucky/about-passive-event-listeners-224ff620e68c

**Comment by extr0py** [comment]
For the main scroll scenario - scrolling a Window in Neovim - we actually handle that really outside the browser infrastructure. So the passive event listeners unfortunately won't be helpful there.

There are a few proposals in #88. The bottleneck at the moment is rendering - we basically re-render _every line that changes_, which since most lines move in a scroll, is a lot of rendering!

There are definitely some ways we can improve that, though. Canvas even supports a way to translate a section of the canvas, which would be worth trying out.
