### ISSUE TITLE
Open from command line

### ISSUE THREAD

**Issue by mhartington** [extr0py/oni#636]
Similar to VSCode, Atom, and VimR, Oni should offer a command line script that starts the editor in the current directory.  I have a simple  one for vscode

```
function code () {
  VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $*
}
```

Or something more complicated like atom 

<details>

```bash
#!/bin/bash

if [ "$(uname)" == 'Darwin' ]; then
  OS='Mac'
elif [ "$(expr substr $(uname -s) 1 5)" == 'Linux' ]; then
  OS='Linux'
else
  echo "Your platform ($(uname -a)) is not supported."
  exit 1
fi

if [ "$(basename $0)" == 'atom-beta' ]; then
  BETA_VERSION=true
else
  BETA_VERSION=
fi

export ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=true

while getopts ":wtfvh-:" opt; do
  case "$opt" in
    -)
      case "${OPTARG}" in
        wait)
          WAIT=1
          ;;
        help|version)
          REDIRECT_STDERR=1
          EXPECT_OUTPUT=1
          ;;
        foreground|benchmark|benchmark-test|test)
          EXPECT_OUTPUT=1
          ;;
      esac
      ;;
    w)
      WAIT=1
      ;;
    h|v)
      REDIRECT_STDERR=1
      EXPECT_OUTPUT=1
      ;;
    f|t)
      EXPECT_OUTPUT=1
      ;;
  esac
done

if [ $REDIRECT_STDERR ]; then
  exec 2> /dev/null
fi

if [ $EXPECT_OUTPUT ]; then
  export ELECTRON_ENABLE_LOGGING=1
fi

if [ $OS == 'Mac' ]; then
  if [ -L "$0" ]; then
    SCRIPT="$(readlink "$0")"
  else
    SCRIPT="$0"
  fi
  ATOM_APP="$(dirname "$(dirname "$(dirname "$(dirname "$SCRIPT")")")")"
  if [ "$ATOM_APP" == . ]; then
    unset ATOM_APP
  else
    ATOM_PATH="$(dirname "$ATOM_APP")"
    ATOM_APP_NAME="$(basename "$ATOM_APP")"
  fi

  if [ -n "$BETA_VERSION" ]; then
    ATOM_EXECUTABLE_NAME="Atom Beta"
  else
    ATOM_EXECUTABLE_NAME="Atom"
  fi

  if [ -z "${ATOM_PATH}" ]; then
    # If ATOM_PATH isn't set, check /Applications and then ~/Applications for Atom.app
    if [ -x "/Applications/$ATOM_APP_NAME" ]; then
      ATOM_PATH="/Applications"
    elif [ -x "$HOME/Applications/$ATOM_APP_NAME" ]; then
      ATOM_PATH="$HOME/Applications"
    else
      # We haven't found an Atom.app, use spotlight to search for Atom
      ATOM_PATH="$(mdfind "kMDItemCFBundleIdentifier == 'com.github.atom'" | grep -v ShipIt | head -1 | xargs -0 dirname)"

      # Exit if Atom can't be found
      if [ ! -x "$ATOM_PATH/$ATOM_APP_NAME" ]; then
        echo "Cannot locate ${ATOM_APP_NAME}, it is usually located in /Applications. Set the ATOM_PATH environment variable to the directory containing ${ATOM_APP_NAME}."
        exit 1
      fi
    fi
  fi

  if [ $EXPECT_OUTPUT ]; then
    "$ATOM_PATH/$ATOM_APP_NAME/Contents/MacOS/$ATOM_EXECUTABLE_NAME" --executed-from="$(pwd)" --pid=$$ "$@"
    exit $?
  else
    open -a "$ATOM_PATH/$ATOM_APP_NAME" -n --args --executed-from="$(pwd)" --pid=$$ --path-environment="$PATH" "$@"
  fi
elif [ $OS == 'Linux' ]; then
  SCRIPT=$(readlink -f "$0")
  USR_DIRECTORY=$(readlink -f $(dirname $SCRIPT)/..)

  if [ -n "$BETA_VERSION" ]; then
    ATOM_PATH="$USR_DIRECTORY/share/atom-beta/atom"
  else
    ATOM_PATH="$USR_DIRECTORY/share/atom/atom"
  fi

  ATOM_HOME="${ATOM_HOME:-$HOME/.atom}"
  mkdir -p "$ATOM_HOME"

  : ${TMPDIR:=/tmp}

  [ -x "$ATOM_PATH" ] || ATOM_PATH="$TMPDIR/atom-build/Atom/atom"

  if [ $EXPECT_OUTPUT ]; then
    "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@"
    exit $?
  else
    (
    nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
    if [ $? -ne 0 ]; then
      cat "$ATOM_HOME/nohup.out"
      exit $?
    fi
    ) &
  fi
fi

# Exits this process when Atom is used as $EDITOR
on_die() {
  exit 0
}
trap 'on_die' SIGQUIT SIGTERM

# If the wait flag is set, don't exit this process until Atom tells it to.
if [ $WAIT ]; then
  while true; do
    sleep 1
  done
fi

```

</details>

**Comment by cyansprite** [comment]
Perhaps we could handle if we get a folder as a parameter, we should open it to that directory, we don't need flags really, just

```
oni ~/Documents/oni
```

We can check was the argument a directory, if so then chdir to it, otherwise use the current working directory.

Right now whatever directory you are in on the command line will open that directory, we should have a more robust approach.

If we get multiple parameters say

```
oni ~/Documents/oni/ ~/.config/nvim/init.vim
```
we should open both, and change to the one that is a directory.

In the case of

```
oni ~/Documents/oni ~/Documents
```

We should honor the first option and ignore the second.

**Comment by extr0py** [comment]
Yes, this is a big pain point in OSX still! (@CrossR just fixed this in Windows, by adding Oni to the %PATH% during install in #613).

@cyansprite - I think the issue is, if you install on OSX via the .dmg (or .zip), the shell doesn't know about `oni` at all (if you install from source, and run `npm link`, you get it from the link step).

There was some discussion in #346 about adding a command to the 'command palette' to install Oni to the path (which is what VSCode does - it shells out to create a symlink to `/usr/local/bin`, I believe). I didn't know about the `VSCODE_CWD` strategy until now, though!

It seems like if we had something similiar - like an environment variable called `ONI_CWD` - and gave details about updating the bash profile in our installation steps, that could be a good shorter-term resolution.

**Comment by cyansprite** [comment]
> It seems like if we had something similiar - like an environment variable called ONI_CWD - and gave details about updating the bash profile in our installation steps, that could be a good shorter-term resolution.

As a short-term resolution I could see this working, but for the long term we shouldn't trust environment variables, it's better to have some kind of initial value support. Adding to the path would probably be the best solution, I'm not sure how to mac so sadly that's all I have to offer.

**Comment by pierreozoux** [comment]
Hello!

Just installed in OSX (with brew) to try it out, and:

```
cd /tmp
oni test
```

But it doesn't try to create this new file. I'm sure I missed something, but I'd be glad to know, or if I should open a new issue?

Thanks!
