### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by pacuna** [extr0py/oni#7]
I'm getting this error on MacOs sierra. I found some similar issues with other packages and apparently it has to do with line ending format?

**Comment by TomatoMus** [comment]
I can solve it in the following way.
```
$vim /your/oni/path/oni

:set ff=unix
:w
```

**Comment by pacuna** [comment]
I solved by building it myself.

**Comment by extr0py** [comment]
Thanks @TomatoMus  and @pacuna  for the details!

Ya, looks related to the issue with npm/npm#12371. I've been doing the publish from a Windows machine, which hits this issue. Hopefully the fix to convert the line endings prior to publish will address this.

Cloning and building will work fine, since git auto-converts the line endings when you check out. Glad that works ok :)
